{
  "openapi": "3.0.1",
  "info": {
    "title": "Stack Overflow for Teams API",
    "version": "v3"
  },
  "servers": [
    {
      "url": "https://support-autotest.stackenterprise.co/api/v3"
    }
  ],
  "paths": {
    "/questions": {
      "get": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Retrieve all questions",
        "description": "Retrieves all questions on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Create a question",
        "description": "Creates a question.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions": {
      "get": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Retrieve all questions",
        "description": "Retrieves all questions on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Create a question",
        "description": "Creates a question.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}": {
      "get": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Retrieve a question",
        "description": "Retrieves a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Update a question",
        "description": "Updates a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Delete a question",
        "description": "Deletes a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}": {
      "get": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Retrieve a question",
        "description": "Retrieves a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Update a question",
        "description": "Updates a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Delete a question",
        "description": "Deletes a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/linked": {
      "get": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Retrieve linked questions",
        "description": "Retrieves questions linked to another question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/linked": {
      "get": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Retrieve linked questions",
        "description": "Retrieves questions linked to another question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/related": {
      "get": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Retrieve related questions",
        "description": "Retrieves questions related to another question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/related": {
      "get": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Retrieve related questions",
        "description": "Retrieves questions related to another question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/flags/options": {
      "get": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Retrieve list of flag options",
        "description": "Retrieve a list of flag options for a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/flags/options": {
      "get": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Retrieve list of flag options",
        "description": "Retrieve a list of flag options for a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/upvote": {
      "post": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Upvote a question",
        "description": "Upvotes a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Delete question upvote",
        "description": "Deletes the upvote of a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/upvote": {
      "post": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Upvote a question",
        "description": "Upvotes a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Delete question upvote",
        "description": "Deletes the upvote of a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/downvote": {
      "post": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Downvote a question",
        "description": "Downvote a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Delete question downvote",
        "description": "Deletes the downvote of a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/downvote": {
      "post": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Downvote a question",
        "description": "Downvote a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Delete question downvote",
        "description": "Deletes the downvote of a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/bookmark": {
      "post": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Bookmark question",
        "description": "Bookmarks a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Unbookmark question",
        "description": "Unbookmarks a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/bookmark": {
      "post": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Bookmark question",
        "description": "Bookmarks a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Unbookmark question",
        "description": "Unbookmarks a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/flags": {
      "post": {
        "tags": [
          "Questions - Main"
        ],
        "summary": "Raises a flag for a question",
        "description": "Raises a flag for a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/flags": {
      "post": {
        "tags": [
          "Questions - Teams"
        ],
        "summary": "Raises a flag for a question",
        "description": "Raises a flag for a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers": {
      "get": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Retrieve all answers to a question",
        "description": "Retrieves all answers to a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Create an answer",
        "description": "Creates an answer to a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers": {
      "get": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Retrieve all answers to a question",
        "description": "Retrieves all answers to a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Create an answer",
        "description": "Creates an answer to a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}": {
      "get": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Retrieve an answer",
        "description": "Retrieves an answer to a question, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Update an answer",
        "description": "Updates an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Delete an answer",
        "description": "Deletes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}": {
      "get": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Retrieve an answer",
        "description": "Retrieves an answer to a question, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Update an answer",
        "description": "Updates an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Delete an answer",
        "description": "Deletes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/flags/options": {
      "get": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Retrive a list of flag options",
        "description": "Retrieve a list of flag options for an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/flags/options": {
      "get": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Retrive a list of flag options",
        "description": "Retrieve a list of flag options for an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/upvote": {
      "post": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Upvote an answer",
        "description": "Upvotes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Delete answer upvote",
        "description": "Deletes the upvote of an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/upvote": {
      "post": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Upvote an answer",
        "description": "Upvotes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Delete answer upvote",
        "description": "Deletes the upvote of an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/downvote": {
      "post": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Downvote an answer",
        "description": "Downvotes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Delete answer downvote",
        "description": "Deletes the downvote of an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/downvote": {
      "post": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Downvote an answer",
        "description": "Downvotes an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Delete answer downvote",
        "description": "Deletes the downvote of an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/accept": {
      "post": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Accept an answer",
        "description": "Accepts an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Unaccept an answer",
        "description": "Unaccepts an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/accept": {
      "post": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Accept an answer",
        "description": "Accepts an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Unaccept an answer",
        "description": "Unaccepts an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/flags": {
      "post": {
        "tags": [
          "Answers - Main"
        ],
        "summary": "Raises a flag for an answer",
        "description": "Raises a flag for an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/flags": {
      "post": {
        "tags": [
          "Answers - Teams"
        ],
        "summary": "Raises a flag for an answer",
        "description": "Raises a flag for an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/articles": {
      "get": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Retrieve all articles",
        "description": "Retrieves all articles on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Create an article",
        "description": "Creates an article.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/articles": {
      "get": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Retrieve all articles",
        "description": "Retrieves all articles on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Create an article",
        "description": "Creates an article.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/articles/{articleId}": {
      "get": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Retrieve an article",
        "description": "Retrieves a article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Update an article",
        "description": "Updates an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Delete an article",
        "description": "Deletes an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/articles/{articleId}": {
      "get": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Retrieve an article",
        "description": "Retrieves a article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Update an article",
        "description": "Updates an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Delete an article",
        "description": "Deletes an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/articles/{articleId}/linked-questions": {
      "get": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Retrieve linked questions",
        "description": "Retrieves questions linked to an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/articles/{articleId}/linked-questions": {
      "get": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Retrieve linked questions",
        "description": "Retrieves questions linked to an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/articles/{articleId}/upvote": {
      "post": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Upvote an article",
        "description": "Upvotes an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Articles - Main"
        ],
        "summary": "Delete article upvote",
        "description": "Deletes the upvote of an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/articles/{articleId}/upvote": {
      "post": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Upvote an article",
        "description": "Upvotes an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Articles - Teams"
        ],
        "summary": "Delete article upvote",
        "description": "Deletes the upvote of an article, identified by Article ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/tags": {
      "get": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Retrieve tags",
        "description": "Queries all tags on the site.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags": {
      "get": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Retrieve tags",
        "description": "Queries all tags on the site.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}": {
      "get": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Retrieve a tag",
        "description": "Retrieves a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}": {
      "get": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Retrieve a tag",
        "description": "Retrieves a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/subject-matter-experts": {
      "get": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Retrieve subject matter experts for a tag",
        "description": "Retrieves the subject matter experts for a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Replace subject matter expert(s) for a tag",
        "description": "Replaces the subject matter expert(s) for a tag, identified by tag ID. Send new user ID(s) and/or user group ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/subject-matter-experts": {
      "get": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Retrieve subject matter experts for a tag",
        "description": "Retrieves the subject matter experts for a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Replace subject matter expert(s) for a tag",
        "description": "Replaces the subject matter expert(s) for a tag, identified by tag ID. Send new user ID(s) and/or user group ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/tag-watchers": {
      "get": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Retrieves users who are tag watchers of the specified tag",
        "description": "Retrieves the tag watchers for a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/tag-watchers": {
      "get": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Retrieves users who are tag watchers of the specified tag",
        "description": "Retrieves the tag watchers for a tag, identified by tag ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/subject-matter-experts/user-groups": {
      "post": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Add user group(s) as subject matter experts to a tag",
        "description": "Adds one or more user groups as subject matter experts to a tag, identified by tag ID and user group ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/subject-matter-experts/user-groups": {
      "post": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Add user group(s) as subject matter experts to a tag",
        "description": "Adds one or more user groups as subject matter experts to a tag, identified by tag ID and user group ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/subject-matter-experts/users": {
      "post": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Add user(s) as subject matter expert(s) to a tag",
        "description": "Adds one or more users as subject matter experts to a tag, identified by tag ID and user ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/subject-matter-experts/users": {
      "post": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Add user(s) as subject matter expert(s) to a tag",
        "description": "Adds one or more users as subject matter experts to a tag, identified by tag ID and user ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/subject-matter-experts/user-groups/{userGroupId}": {
      "delete": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Remove a user group as subject matter experts for a tag",
        "description": "Removes a user group as subject matter experts for a tag, identified by tag ID and user group ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/subject-matter-experts/user-groups/{userGroupId}": {
      "delete": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Remove a user group as subject matter experts for a tag",
        "description": "Removes a user group as subject matter experts for a tag, identified by tag ID and user group ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/tags/{tagId}/subject-matter-experts/users/{userId}": {
      "delete": {
        "tags": [
          "Tags - Main"
        ],
        "summary": "Remove a user as subject matter expert for a tag",
        "description": "Removes a user as subject matter expert for a tag, identified by tag ID and user ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/tags/{tagId}/subject-matter-experts/users/{userId}": {
      "delete": {
        "tags": [
          "Tags - Teams"
        ],
        "summary": "Remove a user as subject matter expert for a tag",
        "description": "Removes a user as subject matter expert for a tag, identified by tag ID and user ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/comments": {
      "get": {
        "tags": [
          "Comments - Main"
        ],
        "summary": "Retrieve comments on a question",
        "description": "Retrieves comments on a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/comments": {
      "get": {
        "tags": [
          "Comments - Teams"
        ],
        "summary": "Retrieve comments on a question",
        "description": "Retrieves comments on a question, identified by question ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/articles/{articleId}/comments": {
      "get": {
        "tags": [
          "Comments - Main"
        ],
        "summary": "Retrieve comments on an article",
        "description": "Retrieves comments on an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/articles/{articleId}/comments": {
      "get": {
        "tags": [
          "Comments - Teams"
        ],
        "summary": "Retrieve comments on an article",
        "description": "Retrieves comments on an article, identified by article ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/questions/{questionId}/answers/{answerId}/comments": {
      "get": {
        "tags": [
          "Comments - Main"
        ],
        "summary": "Retrieve comments on an answer",
        "description": "Retrieves comments on an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/questions/{questionId}/answers/{answerId}/comments": {
      "get": {
        "tags": [
          "Comments - Teams"
        ],
        "summary": "Retrieve comments on an answer",
        "description": "Retrieves comments on an answer, identified by question ID and answer ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/users/me": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieve logged-in user details",
        "description": "Retrieves details for the logged-in user.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users/me": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieve logged-in user details",
        "description": "Retrieves details for the logged-in user.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieve all users",
        "description": "Retrieves all users on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieve all users",
        "description": "Retrieves all users on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/users/{userId}": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieve a user",
        "description": "Retrieves details for a user, identified by user ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users/{userId}": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieve a user",
        "description": "Retrieves details for a user, identified by user ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/users/by-email/{email}": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieve a user by email address",
        "security": [
          {
            "oauth2": [
              "RequireAdminRole",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users/by-email/{email}": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieve a user by email address",
        "security": [
          {
            "oauth2": [
              "RequireAdminRole",
              null
            ]
          }
        ]
      }
    },
    "/users/{userId}/watched-tags": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieves a list of tags watched by user",
        "description": "Retrieves watched tags, identified by tag name.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users/{userId}/watched-tags": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieves a list of tags watched by user",
        "description": "Retrieves watched tags, identified by tag name.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/users/by-external-id/{externalId}": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Retrieve a user by external ID",
        "security": [
          {
            "oauth2": [
              "RequireAdminRole",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/users/by-external-id/{externalId}": {
      "get": {
        "tags": [
          "Users - Teams"
        ],
        "summary": "Retrieve a user by external ID",
        "security": [
          {
            "oauth2": [
              "RequireAdminRole",
              null
            ]
          }
        ]
      }
    },
    "/users/manage": {
      "get": {
        "tags": [
          "Users - Main"
        ],
        "summary": "Manage all users",
        "description": "Retrieves all users on the site or team, for user management.",
        "security": [
          {
            "oauth2": [
              "RequireAdminRole",
              null
            ]
          }
        ]
      }
    },
    "/user-groups": {
      "get": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Retrieve all user groups",
        "description": "Retrieves all user groups on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Create a user group",
        "description": "Creates a user group.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/user-groups": {
      "get": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Retrieve all user groups",
        "description": "Retrieves all user groups on the site or team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Create a user group",
        "description": "Creates a user group.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/user-groups/{userGroupId}": {
      "get": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Retrieve a user group",
        "description": "Retrieves a user group, identified by user group ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Update a user group",
        "description": "Updates a user group, identified by user group ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/user-groups/{userGroupId}": {
      "get": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Retrieve a user group",
        "description": "Retrieves a user group, identified by user group ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Update a user group",
        "description": "Updates a user group, identified by user group ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/user-groups/{userGroupId}/members": {
      "post": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Add member(s) to a user group",
        "description": "Adds one or more members to a user group, identified by user group ID and user ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/user-groups/{userGroupId}/members": {
      "post": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Add member(s) to a user group",
        "description": "Adds one or more members to a user group, identified by user group ID and user ID(s).",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/user-groups/{userGroupId}/members/{userId}": {
      "delete": {
        "tags": [
          "UserGroups - Main"
        ],
        "summary": "Delete a member from a user group",
        "description": "Deletes a member from a user group, identified by user group ID and user ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/user-groups/{userGroupId}/members/{userId}": {
      "delete": {
        "tags": [
          "UserGroups - Teams"
        ],
        "summary": "Delete a member from a user group",
        "description": "Deletes a member from a user group, identified by user group ID and user ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/search": {
      "get": {
        "tags": [
          "Search - Main"
        ],
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/search": {
      "get": {
        "tags": [
          "Search - Teams"
        ],
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/communities": {
      "get": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Retrieves all communities on the site.",
        "description": "Queries all communities on the site.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/communities/{communityId}": {
      "get": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Retrieve a community",
        "description": "Retrieves a community, identified by community ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      }
    },
    "/communities/{communityId}/join": {
      "post": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Join a community",
        "description": "Adds current user to a community, identified by community ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/communities/{communityId}/join/bulk": {
      "post": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Join multiple users to a community",
        "description": "Adds the given users by ID to a community, identified by community ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/communities/{communityId}/leave": {
      "post": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Leave a community",
        "description": "Remove current user from a community, identified by community ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/communities/{communityId}/leave/bulk": {
      "post": {
        "tags": [
          "Communities - Main"
        ],
        "summary": "Leave a community for multiple users",
        "description": "Remove the given users by ID from a community, identified by community ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/collections": {
      "get": {
        "tags": [
          "Collections - Main"
        ],
        "summary": "Retrieve all collections",
        "description": "Retrieves all collections for the full site or specified team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Collections - Main"
        ],
        "summary": "Create a collection",
        "description": "Creates a collection.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/collections": {
      "get": {
        "tags": [
          "Collections - Teams"
        ],
        "summary": "Retrieve all collections",
        "description": "Retrieves all collections for the full site or specified team.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Collections - Teams"
        ],
        "summary": "Create a collection",
        "description": "Creates a collection.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/collections/{collectionId}": {
      "get": {
        "tags": [
          "Collections - Main"
        ],
        "summary": "Retrieve a collection",
        "description": "Retrieves a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Collections - Main"
        ],
        "summary": "Update a collection",
        "description": "Updates a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Collections - Main"
        ],
        "summary": "Delete a collection",
        "description": "Deletes a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/collections/{collectionId}": {
      "get": {
        "tags": [
          "Collections - Teams"
        ],
        "summary": "Retrieve a collection",
        "description": "Retrieves a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              null
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Collections - Teams"
        ],
        "summary": "Update a collection",
        "description": "Updates a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Collections - Teams"
        ],
        "summary": "Delete a collection",
        "description": "Deletes a collection, identified by collection ID.",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/images/{imageId}": {
      "get": {
        "tags": [
          "Images - Main"
        ],
        "summary": "Gets an image by Id.",
        "description": "This endpoint retrieves an image file given its id.",
        "security": [
          {
            "oauth2": [
              "RequireAccessToken",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/images/{imageId}": {
      "get": {
        "tags": [
          "Images - Teams"
        ],
        "summary": "Gets an image by Id.",
        "description": "This endpoint retrieves an image file given its id.",
        "security": [
          {
            "oauth2": [
              "RequireAccessToken",
              null
            ]
          }
        ]
      }
    },
    "/images/upload": {
      "post": {
        "tags": [
          "Images - Main"
        ],
        "summary": "Uploads an image file.",
        "description": "This endpoint uploads an image file and returns the URI of the uploaded image if successful. \nSupported file types: jpeg, png, gif, bmp, webp (Max size 2 MiB)",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/teams/{team}/images/upload": {
      "post": {
        "tags": [
          "Images - Teams"
        ],
        "summary": "Uploads an image file.",
        "description": "This endpoint uploads an image file and returns the URI of the uploaded image if successful. \nSupported file types: jpeg, png, gif, bmp, webp (Max size 2 MiB)",
        "security": [
          {
            "oauth2": [
              "RequireWriteAccess",
              null
            ]
          }
        ]
      }
    },
    "/stacky": {
      "get": {
        "tags": [
          "Stacky - Main"
        ],
        "summary": "Retrieve Stacky ASCII art",
        "description": "Retrieves Stacky ASCII art (useful for testing)."
      }
    }
  },
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://support-autotest.stackenterprise.co/oauth",
            "tokenUrl": "https://support-autotest.stackenterprise.co/oauth/access_token/json",
            "scopes": {
              "write_access": "Allow write access",
              "access_team": "Access a team"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "oauth2": [ ]
    }
  ]
}