/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ArticlePermissionsType } from './ArticlePermissionsType';
import { UserGroupResponseModel } from './UserGroupResponseModel';
import { UserSummaryResponseModel } from './UserSummaryResponseModel';
import { HttpFile } from '../http/http';

export class ArticlePermissionsResponseModel {
    'editableBy'?: ArticlePermissionsType;
    /**
    * Editor Users. The individual users who can edit this article
    */
    'editorUsers'?: Array<UserSummaryResponseModel>;
    /**
    * Editor User Groups. The user groups that can edit this article
    */
    'editorUserGroups'?: Array<UserGroupResponseModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "editableBy",
            "baseName": "editableBy",
            "type": "ArticlePermissionsType",
            "format": ""
        },
        {
            "name": "editorUsers",
            "baseName": "editorUsers",
            "type": "Array<UserSummaryResponseModel>",
            "format": ""
        },
        {
            "name": "editorUserGroups",
            "baseName": "editorUserGroups",
            "type": "Array<UserGroupResponseModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ArticlePermissionsResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}


