/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommunityMemberResponseModel } from './CommunityMemberResponseModel';
import { TagSummaryResponseModel } from './TagSummaryResponseModel';
import { HttpFile } from '../http/http';

export class CommunityResponseModel {
    /**
    * Members. The community\'s members.
    */
    'members'?: Array<CommunityMemberResponseModel>;
    /**
    * Name. The community\'s name.
    */
    'name'?: string;
    /**
    * Description. The community\'s description.
    */
    'description'?: string;
    /**
    * ID. The community\'s ID.
    */
    'id'?: number;
    /**
    * Member count. Number of members in the community.
    */
    'memberCount'?: number;
    /**
    * Tags. The community\'s tags.
    */
    'tags'?: Array<TagSummaryResponseModel>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "members",
            "baseName": "members",
            "type": "Array<CommunityMemberResponseModel>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "memberCount",
            "baseName": "memberCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagSummaryResponseModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommunityResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}
