/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CommunityMemberResponseModel {
    /**
    * ID. The member\'s user ID.
    */
    'id'?: number;
    /**
    * Name. The member\'s name.
    */
    'name'?: string;
    /**
    * Member since. The date and time the member joined the community.
    */
    'memberSince'?: Date;
    /**
    * Is SME. Returns true if the member is an SME (subject matter expert) for one or more of the community\'s tags.
    */
    'isSme'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "memberSince",
            "baseName": "memberSince",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "isSme",
            "baseName": "isSme",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommunityMemberResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}
