/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TagSummaryResponseModel } from './TagSummaryResponseModel';
import { UserSummaryResponseModel } from './UserSummaryResponseModel';
import { HttpFile } from '../http/http';

export class QuestionSearchResultModel {
    'type'?: string;
    'questionId'?: number;
    'answerCount'?: number;
    'hasAcceptedAnswer'?: boolean;
    'viewCount'?: number;
    'title'?: string;
    'snippet'?: string;
    'tags'?: Array<TagSummaryResponseModel>;
    'owner'?: UserSummaryResponseModel;
    'creationDate'?: Date;
    'score'?: number;
    'webUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "questionId",
            "baseName": "questionId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "answerCount",
            "baseName": "answerCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "hasAcceptedAnswer",
            "baseName": "hasAcceptedAnswer",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "viewCount",
            "baseName": "viewCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "snippet",
            "baseName": "snippet",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Array<TagSummaryResponseModel>",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "UserSummaryResponseModel",
            "format": ""
        },
        {
            "name": "creationDate",
            "baseName": "creationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "webUrl",
            "baseName": "webUrl",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QuestionSearchResultModel.attributeTypeMap;
    }

    public constructor() {
    }
}
