/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class UserSummaryResponseModel {
    /**
    * ID. The user\'s unique identifier on this site.
    */
    'id'?: number;
    /**
    * Account ID. The user\'s unique account identifier across all Stack Overflow sites.
    */
    'accountId'?: number | null;
    /**
    * Name. The user\'s name.
    */
    'name'?: string;
    /**
    * Avatar URL. The URL to the user\'s avatar (profile picture).
    */
    'avatarUrl'?: string;
    /**
    * URL. The URL to the user\'s profile.
    */
    'webUrl'?: string;
    /**
    * Reputation. The user\'s numerical reputation.
    */
    'reputation'?: number;
    /**
    * Role. The user\'s role on the site.
    */
    'role'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "accountId",
            "baseName": "accountId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "avatarUrl",
            "baseName": "avatarUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "webUrl",
            "baseName": "webUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "reputation",
            "baseName": "reputation",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserSummaryResponseModel.attributeTypeMap;
    }

    public constructor() {
    }
}
